# Generated by Django 6.0.1 on 2026-05-20 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('num_huespedes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unidades_reservadas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hospedaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='parques.hospedaje')),
            ],
        ),
    ]
