# Generated by Django 6.0.1 on 2026-05-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reservacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio__lt', models.F('fecha_fin'))), name='fecha_inicio_menor_fecha_fin'),
        ),
    ]
