# Generated by Django 6.0.1 on 2026-05-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospedaje',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='activo',
        ),
    ]
