# Generated by Django 6.0.5 on 2026-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0002_remove_hospedaje_activo_remove_parque_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='estado',
            field=models.CharField(choices=[('TLAXCALA', 'Tlaxcala'), ('EDOMEX', 'Estado de México'), ('PUEBLA', 'Puebla')], default='TLAXCALA', max_length=20),
        ),
    ]
