# Generated by Django 6.0.5 on 2026-05-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0003_parque_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='parque',
            constraint=models.UniqueConstraint(fields=('latitud', 'longitud'), name='unique_coordinates'),
        ),
    ]
